# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from src.screens.screen_functions.stacked_widget_subclass import MyStackWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 869)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = MyStackWidget()
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setObjectName("stackedWidget")
        self.start_page = QtWidgets.QWidget()
        self.start_page.setObjectName("start_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.start_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.search_btn = QtWidgets.QPushButton(self.start_page)
        self.search_btn.setObjectName("search_btn")
        self.gridLayout.addWidget(self.search_btn, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        self.serialized_btn = QtWidgets.QPushButton(self.start_page)
        self.serialized_btn.setObjectName("serialized_btn")
        self.gridLayout.addWidget(self.serialized_btn, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.start_page)
        self.search_result_page = QtWidgets.QWidget()
        self.search_result_page.setObjectName("search_result_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.search_result_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.back_btn_search_result = QtWidgets.QPushButton(self.search_result_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn_search_result.sizePolicy().hasHeightForWidth())
        self.back_btn_search_result.setSizePolicy(sizePolicy)
        self.back_btn_search_result.setObjectName("back_btn_search_result")
        self.gridLayout_2.addWidget(self.back_btn_search_result, 1, 1, 1, 1)
        self.search_result_table = QtWidgets.QTableWidget(self.search_result_page)
        self.search_result_table.setObjectName("search_result_table")
        self.search_result_table.setColumnCount(14)
        self.search_result_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(13, item)
        self.gridLayout_2.addWidget(self.search_result_table, 0, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(353, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(353, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.search_result_page)
        self.search_page = QtWidgets.QWidget()
        self.search_page.setObjectName("search_page")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.search_page)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 0, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_7 = QtWidgets.QLabel(self.search_page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.search_page)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.search_page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.last_search = QtWidgets.QLineEdit(self.search_page)
        self.last_search.setText("")
        self.last_search.setObjectName("last_search")
        self.gridLayout_7.addWidget(self.last_search, 5, 1, 1, 2)
        self.general_radio = QtWidgets.QRadioButton(self.search_page)
        self.general_radio.setText("")
        self.general_radio.setObjectName("general_radio")
        self.gridLayout_7.addWidget(self.general_radio, 7, 0, 1, 2)
        self.first_search = QtWidgets.QLineEdit(self.search_page)
        self.first_search.setText("")
        self.first_search.setObjectName("first_search")
        self.gridLayout_7.addWidget(self.first_search, 3, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.search_page)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.last_radio = QtWidgets.QRadioButton(self.search_page)
        self.last_radio.setText("")
        self.last_radio.setObjectName("last_radio")
        self.gridLayout_7.addWidget(self.last_radio, 5, 0, 1, 1)
        self.first_radio = QtWidgets.QRadioButton(self.search_page)
        self.first_radio.setText("")
        self.first_radio.setObjectName("first_radio")
        self.gridLayout_7.addWidget(self.first_radio, 3, 0, 1, 1)
        self.general_search = QtWidgets.QLineEdit(self.search_page)
        self.general_search.setText("")
        self.general_search.setObjectName("general_search")
        self.gridLayout_7.addWidget(self.general_search, 7, 2, 1, 1)
        self.phone_radio = QtWidgets.QRadioButton(self.search_page)
        self.phone_radio.setText("")
        self.phone_radio.setObjectName("phone_radio")
        self.gridLayout_7.addWidget(self.phone_radio, 1, 0, 1, 1)
        self.phone_search = QtWidgets.QLineEdit(self.search_page)
        self.phone_search.setText("")
        self.phone_search.setObjectName("phone_search")
        self.gridLayout_7.addWidget(self.phone_search, 1, 1, 1, 2)
        self.submit_search_btn = QtWidgets.QPushButton(self.search_page)
        self.submit_search_btn.setObjectName("submit_search_btn")
        self.gridLayout_7.addWidget(self.submit_search_btn, 8, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 1, 2, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_6)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 0, 0, 1, 1)
        self.back_btn_search = QtWidgets.QPushButton(self.search_page)
        self.back_btn_search.setObjectName("back_btn_search")
        self.gridLayout_5.addWidget(self.back_btn_search, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem12, 0, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem13, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_5)
        self.verticalLayout_11.setStretch(0, 15)
        self.verticalLayout_11.setStretch(1, 8)
        self.verticalLayout_11.setStretch(2, 5)
        self.gridLayout_13.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.search_page)
        self.serialized_page = QtWidgets.QWidget()
        self.serialized_page.setObjectName("serialized_page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.serialized_page)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.serial_table = QtWidgets.QTableWidget(self.serialized_page)
        self.serial_table.setObjectName("serial_table")
        self.serial_table.setColumnCount(5)
        self.serial_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.serial_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.serial_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.serial_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.serial_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.serial_table.setHorizontalHeaderItem(4, item)
        self.gridLayout_8.addWidget(self.serial_table, 0, 0, 1, 3)
        spacerItem14 = QtWidgets.QSpacerItem(404, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem14, 1, 0, 1, 1)
        self.back_btn_serial = QtWidgets.QPushButton(self.serialized_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn_serial.sizePolicy().hasHeightForWidth())
        self.back_btn_serial.setSizePolicy(sizePolicy)
        self.back_btn_serial.setMinimumSize(QtCore.QSize(200, 0))
        self.back_btn_serial.setMaximumSize(QtCore.QSize(200, 16777215))
        self.back_btn_serial.setObjectName("back_btn_serial")
        self.gridLayout_8.addWidget(self.back_btn_serial, 1, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(406, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem15, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.serialized_page)
        self.sro_page = QtWidgets.QWidget()
        self.sro_page.setObjectName("sro_page")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.sro_page)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sro_basic_table = QtWidgets.QTableWidget(self.sro_page)
        self.sro_basic_table.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sro_basic_table.sizePolicy().hasHeightForWidth())
        self.sro_basic_table.setSizePolicy(sizePolicy)
        self.sro_basic_table.setMaximumSize(QtCore.QSize(16777215, 308))
        self.sro_basic_table.setObjectName("sro_basic_table")
        self.sro_basic_table.setColumnCount(1)
        self.sro_basic_table.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setHorizontalHeaderItem(0, item)
        self.verticalLayout_3.addWidget(self.sro_basic_table)
        self.sro_back_btn = QtWidgets.QPushButton(self.sro_page)
        self.sro_back_btn.setObjectName("sro_back_btn")
        self.verticalLayout_3.addWidget(self.sro_back_btn)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 0, 0, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.sro_page)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.service_text = QtWidgets.QTextBrowser(self.sro_page)
        self.service_text.setObjectName("service_text")
        self.verticalLayout_2.addWidget(self.service_text)
        self.gridLayout_9.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.sro_page)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.work_text = QtWidgets.QTextBrowser(self.sro_page)
        self.work_text.setObjectName("work_text")
        self.verticalLayout.addWidget(self.work_text)
        self.gridLayout_9.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.sro_page)
        self.customer_page = QtWidgets.QWidget()
        self.customer_page.setObjectName("customer_page")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.customer_page)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.back_btn_customer = QtWidgets.QPushButton(self.customer_page)
        self.back_btn_customer.setObjectName("back_btn_customer")
        self.gridLayout_10.addWidget(self.back_btn_customer, 0, 0, 1, 1)
        self.customer_table_1 = QtWidgets.QTableWidget(self.customer_page)
        self.customer_table_1.setMaximumSize(QtCore.QSize(251, 231))
        self.customer_table_1.setObjectName("customer_table_1")
        self.customer_table_1.setColumnCount(1)
        self.customer_table_1.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.customer_table_1.setHorizontalHeaderItem(0, item)
        self.gridLayout_10.addWidget(self.customer_table_1, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.customer_table_2 = QtWidgets.QTableWidget(self.customer_page)
        self.customer_table_2.setMaximumSize(QtCore.QSize(241, 231))
        self.customer_table_2.setObjectName("customer_table_2")
        self.customer_table_2.setColumnCount(1)
        self.customer_table_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.customer_table_2.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_4.addWidget(self.customer_table_2)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.customer_page)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.layaways_table = QtWidgets.QTableWidget(self.customer_page)
        self.layaways_table.setObjectName("layaways_table")
        self.layaways_table.setColumnCount(3)
        self.layaways_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaways_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaways_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaways_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_17.addWidget(self.layaways_table)
        self.horizontalLayout_4.addLayout(self.verticalLayout_17)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 0, 2, 1, 2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.customer_page)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.phone_tbox = QtWidgets.QTextBrowser(self.customer_page)
        self.phone_tbox.setObjectName("phone_tbox")
        self.verticalLayout_6.addWidget(self.phone_tbox)
        self.gridLayout_10.addLayout(self.verticalLayout_6, 1, 0, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.customer_page)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.notes_tbox = QtWidgets.QTextBrowser(self.customer_page)
        self.notes_tbox.setObjectName("notes_tbox")
        self.verticalLayout_5.addWidget(self.notes_tbox)
        self.gridLayout_10.addLayout(self.verticalLayout_5, 1, 2, 1, 2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.customer_page)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.transactions_table = QtWidgets.QTableWidget(self.customer_page)
        self.transactions_table.setMinimumSize(QtCore.QSize(521, 0))
        self.transactions_table.setObjectName("transactions_table")
        self.transactions_table.setColumnCount(5)
        self.transactions_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(4, item)
        self.verticalLayout_7.addWidget(self.transactions_table)
        self.gridLayout_10.addLayout(self.verticalLayout_7, 2, 0, 1, 3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.customer_page)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.sro_table = QtWidgets.QTableWidget(self.customer_page)
        self.sro_table.setMaximumSize(QtCore.QSize(401, 16777215))
        self.sro_table.setObjectName("sro_table")
        self.sro_table.setColumnCount(6)
        self.sro_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.sro_table)
        self.gridLayout_10.addLayout(self.verticalLayout_4, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.customer_page)
        self.sale_page = QtWidgets.QWidget()
        self.sale_page.setObjectName("sale_page")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.sale_page)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem16)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.sale_page)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.sale_basic_info = QtWidgets.QTableWidget(self.sale_page)
        self.sale_basic_info.setMinimumSize(QtCore.QSize(261, 231))
        self.sale_basic_info.setMaximumSize(QtCore.QSize(261, 231))
        self.sale_basic_info.setObjectName("sale_basic_info")
        self.sale_basic_info.setColumnCount(1)
        self.sale_basic_info.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setHorizontalHeaderItem(0, item)
        self.verticalLayout_8.addWidget(self.sale_basic_info)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.sale_page)
        self.label_2.setMinimumSize(QtCore.QSize(36, 17))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.sale_totals = QtWidgets.QTableWidget(self.sale_page)
        self.sale_totals.setMinimumSize(QtCore.QSize(201, 311))
        self.sale_totals.setMaximumSize(QtCore.QSize(201, 311))
        self.sale_totals.setObjectName("sale_totals")
        self.sale_totals.setColumnCount(1)
        self.sale_totals.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setHorizontalHeaderItem(0, item)
        self.verticalLayout_9.addWidget(self.sale_totals)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.back_btn_sale = QtWidgets.QPushButton(self.sale_page)
        self.back_btn_sale.setObjectName("back_btn_sale")
        self.verticalLayout_10.addWidget(self.back_btn_sale)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem17)
        self.gridLayout_12.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem18, 0, 0, 1, 1)
        self.sale_lines_table = QtWidgets.QTableWidget(self.sale_page)
        self.sale_lines_table.setObjectName("sale_lines_table")
        self.sale_lines_table.setColumnCount(5)
        self.sale_lines_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_lines_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_lines_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_lines_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_lines_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_lines_table.setHorizontalHeaderItem(4, item)
        self.gridLayout_11.addWidget(self.sale_lines_table, 1, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem19, 1, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem20, 2, 0, 1, 1)
        self.gridLayout_11.setColumnStretch(0, 95)
        self.gridLayout_11.setColumnStretch(1, 5)
        self.gridLayout_11.setRowStretch(0, 5)
        self.gridLayout_11.setRowStretch(1, 90)
        self.gridLayout_11.setRowStretch(2, 5)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 1, 1, 1)
        self.gridLayout_12.setColumnStretch(0, 30)
        self.gridLayout_12.setColumnStretch(1, 70)
        self.stackedWidget.addWidget(self.sale_page)
        self.layaway_page = QtWidgets.QWidget()
        self.layaway_page.setObjectName("layaway_page")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.layaway_page)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layaway_table_1 = QtWidgets.QTableWidget(self.layaway_page)
        self.layaway_table_1.setObjectName("layaway_table_1")
        self.layaway_table_1.setColumnCount(1)
        self.layaway_table_1.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.layaway_table_1.setHorizontalHeaderItem(0, item)
        self.horizontalLayout.addWidget(self.layaway_table_1)
        self.layaway_table_2 = QtWidgets.QTableWidget(self.layaway_page)
        self.layaway_table_2.setObjectName("layaway_table_2")
        self.layaway_table_2.setColumnCount(1)
        self.layaway_table_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.layaway_table_2.setHorizontalHeaderItem(0, item)
        self.horizontalLayout.addWidget(self.layaway_table_2)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.layaway_page)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.layaway_initial_notes_tbox = QtWidgets.QTextBrowser(self.layaway_page)
        self.layaway_initial_notes_tbox.setObjectName("layaway_initial_notes_tbox")
        self.verticalLayout_12.addWidget(self.layaway_initial_notes_tbox)
        self.verticalLayout_15.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.layaway_page)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.layaway_notes_tbox = QtWidgets.QTextBrowser(self.layaway_page)
        self.layaway_notes_tbox.setObjectName("layaway_notes_tbox")
        self.verticalLayout_13.addWidget(self.layaway_notes_tbox)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.gridLayout_14.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem21)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.layaway_page)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_14.addWidget(self.label_15)
        self.layaway_transaction_history_tbox = QtWidgets.QTextBrowser(self.layaway_page)
        self.layaway_transaction_history_tbox.setObjectName("layaway_transaction_history_tbox")
        self.verticalLayout_14.addWidget(self.layaway_transaction_history_tbox)
        self.verticalLayout_16.addLayout(self.verticalLayout_14)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem22)
        self.verticalLayout_16.setStretch(0, 25)
        self.verticalLayout_16.setStretch(1, 70)
        self.gridLayout_14.addLayout(self.verticalLayout_16, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem23)
        self.back_btn_layaway = QtWidgets.QPushButton(self.layaway_page)
        self.back_btn_layaway.setObjectName("back_btn_layaway")
        self.horizontalLayout_3.addWidget(self.back_btn_layaway)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem24)
        self.gridLayout_14.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_14.setColumnStretch(0, 50)
        self.gridLayout_14.setColumnStretch(1, 50)
        self.stackedWidget.addWidget(self.layaway_page)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_btn.setText(_translate("MainWindow", "Run a Search"))
        self.serialized_btn.setText(_translate("MainWindow", "See Serialized Inventory"))
        self.back_btn_search_result.setText(_translate("MainWindow", "Back"))
        item = self.search_result_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.search_result_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First"))
        item = self.search_result_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last"))
        item = self.search_result_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address"))
        item = self.search_result_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "City"))
        item = self.search_result_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "State"))
        item = self.search_result_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Zip"))
        item = self.search_result_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Home Phone"))
        item = self.search_result_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Work Phone"))
        item = self.search_result_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Cell Phone"))
        item = self.search_result_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Added"))
        item = self.search_result_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Last Activity"))
        item = self.search_result_table.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Email"))
        item = self.search_result_table.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Tax Exempt"))
        self.label_7.setText(_translate("MainWindow", "First Name"))
        self.label_4.setText(_translate("MainWindow", "Phone #"))
        self.label_5.setText(_translate("MainWindow", "Last Name"))
        self.label_6.setText(_translate("MainWindow", "General Search"))
        self.submit_search_btn.setText(_translate("MainWindow", "Search"))
        self.back_btn_search.setText(_translate("MainWindow", "Back"))
        item = self.serial_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Make"))
        item = self.serial_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.serial_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Serial #"))
        item = self.serial_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        item = self.serial_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Notes"))
        self.back_btn_serial.setText(_translate("MainWindow", "Back"))
        item = self.sro_basic_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Service ID"))
        item = self.sro_basic_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.sro_basic_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Make"))
        item = self.sro_basic_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Model"))
        item = self.sro_basic_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date In"))
        item = self.sro_basic_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Finished On"))
        item = self.sro_basic_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Picked Up"))
        item = self.sro_basic_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        self.sro_back_btn.setText(_translate("MainWindow", "Back"))
        self.label_8.setText(_translate("MainWindow", "Service Request"))
        self.label_9.setText(_translate("MainWindow", "Work Performed"))
        self.back_btn_customer.setText(_translate("MainWindow", "Back"))
        item = self.customer_table_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.customer_table_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "First"))
        item = self.customer_table_1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last"))
        item = self.customer_table_1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Company"))
        item = self.customer_table_1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.customer_table_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        item = self.customer_table_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.customer_table_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "City"))
        item = self.customer_table_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "State"))
        item = self.customer_table_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Zip"))
        item = self.customer_table_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Last Activity"))
        item = self.customer_table_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        self.label_16.setText(_translate("MainWindow", "Layaways"))
        item = self.layaways_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Start"))
        item = self.layaways_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Balance"))
        item = self.layaways_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Layaway ID"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Potential Phones</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Notes"))
        self.label_13.setText(_translate("MainWindow", "Transactions"))
        item = self.transactions_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.transactions_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Subtotal"))
        item = self.transactions_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tax"))
        item = self.transactions_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total"))
        item = self.transactions_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sale ID"))
        self.label_11.setText(_translate("MainWindow", "SRO"))
        item = self.sro_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date In"))
        item = self.sro_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date Done"))
        item = self.sro_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Picked Up"))
        item = self.sro_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.sro_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Make"))
        item = self.sro_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "SRO ID"))
        self.label.setText(_translate("MainWindow", "Sale Info"))
        item = self.sale_basic_info.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sale ID"))
        item = self.sale_basic_info.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.sale_basic_info.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Customer Name"))
        item = self.sale_basic_info.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        item = self.sale_basic_info.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Is Overring?"))
        item = self.sale_basic_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        self.label_2.setText(_translate("MainWindow", "Totals"))
        item = self.sale_totals.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Subtotal"))
        item = self.sale_totals.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tax"))
        item = self.sale_totals.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total"))
        item = self.sale_totals.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cash"))
        item = self.sale_totals.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Credit"))
        item = self.sale_totals.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Debit"))
        item = self.sale_totals.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Misc"))
        item = self.sale_totals.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        self.back_btn_sale.setText(_translate("MainWindow", "Back"))
        item = self.sale_lines_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.sale_lines_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Unit Cost"))
        item = self.sale_lines_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Item Discount"))
        item = self.sale_lines_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Item Total"))
        item = self.sale_lines_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        item = self.layaway_table_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Layaway ID"))
        item = self.layaway_table_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.layaway_table_1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.layaway_table_1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Start Date"))
        item = self.layaway_table_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        item = self.layaway_table_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pay Received"))
        item = self.layaway_table_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Balance Due"))
        item = self.layaway_table_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Initial Notes</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Notes</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Transaction History</span></p></body></html>"))
        self.back_btn_layaway.setText(_translate("MainWindow", "Back"))


