# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from src.screens.screen_functions.stacked_widget_subclass import MyStackWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1652, 913)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = MyStackWidget()
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setObjectName("stackedWidget")
        self.start_page = QtWidgets.QWidget()
        self.start_page.setObjectName("start_page")
        self.gridLayout = QtWidgets.QGridLayout(self.start_page)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(366, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem1)
        self.label_17 = QtWidgets.QLabel(self.start_page)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_18.addWidget(self.label_17)
        self.verticalLayout_18.setStretch(0, 1)
        self.verticalLayout_18.setStretch(1, 100)
        self.gridLayout.addLayout(self.verticalLayout_18, 0, 1, 1, 3)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem2)
        self.search_btn = QtWidgets.QPushButton(self.start_page)
        self.search_btn.setObjectName("search_btn")
        self.verticalLayout_16.addWidget(self.search_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem3)
        self.serialized_btn = QtWidgets.QPushButton(self.start_page)
        self.serialized_btn.setObjectName("serialized_btn")
        self.verticalLayout_16.addWidget(self.serialized_btn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem4)
        self.verticalLayout_16.setStretch(0, 10)
        self.verticalLayout_16.setStretch(1, 10)
        self.verticalLayout_16.setStretch(2, 2)
        self.verticalLayout_16.setStretch(3, 10)
        self.verticalLayout_16.setStretch(4, 10)
        self.gridLayout.addLayout(self.verticalLayout_16, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(366, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(365, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(365, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 4, 1, 1)
        self.gridLayout.setRowStretch(0, 10)
        self.gridLayout.setRowStretch(1, 10)
        self.gridLayout.setRowStretch(2, 10)
        self.stackedWidget.addWidget(self.start_page)
        self.search_result_page = QtWidgets.QWidget()
        self.search_result_page.setObjectName("search_result_page")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.search_result_page)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.label_18 = QtWidgets.QLabel(self.search_result_page)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_19.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.search_result_table = QtWidgets.QTableWidget(self.search_result_page)
        self.search_result_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.search_result_table.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.search_result_table.setShowGrid(True)
        self.search_result_table.setColumnCount(12)
        self.search_result_table.setObjectName("search_result_table")
        self.search_result_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.search_result_table.setHorizontalHeaderItem(11, item)
        self.search_result_table.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_6.addWidget(self.search_result_table)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 100)
        self.horizontalLayout_6.setStretch(2, 2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(353, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.back_btn_search_result = QtWidgets.QPushButton(self.search_result_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn_search_result.sizePolicy().hasHeightForWidth())
        self.back_btn_search_result.setSizePolicy(sizePolicy)
        self.back_btn_search_result.setObjectName("back_btn_search_result")
        self.horizontalLayout_5.addWidget(self.back_btn_search_result)
        spacerItem13 = QtWidgets.QSpacerItem(353, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_19.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.search_result_page)
        self.search_page = QtWidgets.QWidget()
        self.search_page.setObjectName("search_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.search_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem14 = QtWidgets.QSpacerItem(329, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.search_page)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(329, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 0, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(17, 121, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 1, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(329, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 2, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.phone_radio = QtWidgets.QRadioButton(self.search_page)
        self.phone_radio.setText("")
        self.phone_radio.setObjectName("phone_radio")
        self.gridLayout_7.addWidget(self.phone_radio, 1, 0, 1, 1)
        self.submit_search_btn = QtWidgets.QPushButton(self.search_page)
        self.submit_search_btn.setObjectName("submit_search_btn")
        self.gridLayout_7.addWidget(self.submit_search_btn, 8, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.search_page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.search_page)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.last_radio = QtWidgets.QRadioButton(self.search_page)
        self.last_radio.setText("")
        self.last_radio.setObjectName("last_radio")
        self.gridLayout_7.addWidget(self.last_radio, 5, 0, 1, 1)
        self.phone_search = QtWidgets.QLineEdit(self.search_page)
        self.phone_search.setText("")
        self.phone_search.setObjectName("phone_search")
        self.gridLayout_7.addWidget(self.phone_search, 1, 1, 1, 2)
        self.general_radio = QtWidgets.QRadioButton(self.search_page)
        self.general_radio.setText("")
        self.general_radio.setObjectName("general_radio")
        self.gridLayout_7.addWidget(self.general_radio, 7, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.search_page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.last_search = QtWidgets.QLineEdit(self.search_page)
        self.last_search.setText("")
        self.last_search.setObjectName("last_search")
        self.gridLayout_7.addWidget(self.last_search, 5, 1, 1, 2)
        self.first_radio = QtWidgets.QRadioButton(self.search_page)
        self.first_radio.setText("")
        self.first_radio.setObjectName("first_radio")
        self.gridLayout_7.addWidget(self.first_radio, 3, 0, 1, 1)
        self.first_search = QtWidgets.QLineEdit(self.search_page)
        self.first_search.setText("")
        self.first_search.setObjectName("first_search")
        self.gridLayout_7.addWidget(self.first_search, 3, 1, 1, 2)
        self.general_search = QtWidgets.QLineEdit(self.search_page)
        self.general_search.setText("")
        self.general_search.setObjectName("general_search")
        self.gridLayout_7.addWidget(self.general_search, 7, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.search_page)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 2, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(329, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 2, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 122, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem19, 3, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem20, 0, 0, 1, 1)
        self.back_btn_search = QtWidgets.QPushButton(self.search_page)
        self.back_btn_search.setObjectName("back_btn_search")
        self.gridLayout_5.addWidget(self.back_btn_search, 0, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem21, 0, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem22, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 4, 0, 1, 3)
        self.stackedWidget.addWidget(self.search_page)
        self.serialized_page = QtWidgets.QWidget()
        self.serialized_page.setObjectName("serialized_page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.serialized_page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem23)
        self.label_20 = QtWidgets.QLabel(self.serialized_page)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem24)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem25)
        self.serial_table = QtWidgets.QTableWidget(self.serialized_page)
        self.serial_table.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.serial_table.setObjectName("serial_table")
        self.serial_table.setColumnCount(5)
        self.serial_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.serial_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.serial_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.serial_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.serial_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.serial_table.setHorizontalHeaderItem(4, item)
        self.serial_table.horizontalHeader().setVisible(True)
        self.serial_table.horizontalHeader().setStretchLastSection(True)
        self.serial_table.verticalHeader().setVisible(False)
        self.horizontalLayout_9.addWidget(self.serial_table)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem26)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 100)
        self.horizontalLayout_9.setStretch(2, 2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem27 = QtWidgets.QSpacerItem(404, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem27)
        self.back_btn_serial = QtWidgets.QPushButton(self.serialized_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn_serial.sizePolicy().hasHeightForWidth())
        self.back_btn_serial.setSizePolicy(sizePolicy)
        self.back_btn_serial.setMinimumSize(QtCore.QSize(200, 0))
        self.back_btn_serial.setMaximumSize(QtCore.QSize(200, 16777215))
        self.back_btn_serial.setObjectName("back_btn_serial")
        self.horizontalLayout_8.addWidget(self.back_btn_serial)
        spacerItem28 = QtWidgets.QSpacerItem(406, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem28)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.stackedWidget.addWidget(self.serialized_page)
        self.sro_page = QtWidgets.QWidget()
        self.sro_page.setObjectName("sro_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sro_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem29)
        self.label_21 = QtWidgets.QLabel(self.sro_page)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_10.addWidget(self.label_21)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem30)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem31, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem32)
        self.sro_basic_table = QtWidgets.QTableWidget(self.sro_page)
        self.sro_basic_table.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sro_basic_table.sizePolicy().hasHeightForWidth())
        self.sro_basic_table.setSizePolicy(sizePolicy)
        self.sro_basic_table.setMaximumSize(QtCore.QSize(16777215, 308))
        self.sro_basic_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sro_basic_table.setObjectName("sro_basic_table")
        self.sro_basic_table.setColumnCount(1)
        self.sro_basic_table.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_basic_table.setHorizontalHeaderItem(0, item)
        self.sro_basic_table.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_11.addWidget(self.sro_basic_table)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem33)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.sro_page)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.service_text = QtWidgets.QTextBrowser(self.sro_page)
        self.service_text.setObjectName("service_text")
        self.verticalLayout_2.addWidget(self.service_text)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.sro_page)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.work_text = QtWidgets.QTextBrowser(self.sro_page)
        self.work_text.setObjectName("work_text")
        self.verticalLayout.addWidget(self.work_text)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem34)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 9)
        self.horizontalLayout_11.setStretch(2, 2)
        self.horizontalLayout_11.setStretch(3, 19)
        self.horizontalLayout_11.setStretch(4, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem35)
        self.sro_back_btn = QtWidgets.QPushButton(self.sro_page)
        self.sro_back_btn.setObjectName("sro_back_btn")
        self.horizontalLayout_3.addWidget(self.sro_back_btn)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem36)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 4)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 20)
        self.gridLayout_3.setRowStretch(3, 2)
        self.stackedWidget.addWidget(self.sro_page)
        self.customer_page = QtWidgets.QWidget()
        self.customer_page.setObjectName("customer_page")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.customer_page)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_22 = QtWidgets.QLabel(self.customer_page)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_20.addWidget(self.label_22)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem37 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem37)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.customer_table_1 = QtWidgets.QTableWidget(self.customer_page)
        self.customer_table_1.setMaximumSize(QtCore.QSize(1670000, 231))
        self.customer_table_1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.customer_table_1.setObjectName("customer_table_1")
        self.customer_table_1.setColumnCount(1)
        self.customer_table_1.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.customer_table_1.setHorizontalHeaderItem(0, item)
        self.customer_table_1.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_13.addWidget(self.customer_table_1)
        self.customer_table_2 = QtWidgets.QTableWidget(self.customer_page)
        self.customer_table_2.setMaximumSize(QtCore.QSize(1670000, 231))
        self.customer_table_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.customer_table_2.setObjectName("customer_table_2")
        self.customer_table_2.setColumnCount(1)
        self.customer_table_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customer_table_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.customer_table_2.setHorizontalHeaderItem(0, item)
        self.customer_table_2.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_13.addWidget(self.customer_table_2)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_13)
        spacerItem38 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem38)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_11 = QtWidgets.QLabel(self.customer_page)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_17.addWidget(self.label_11)
        self.sro_table = QtWidgets.QTableWidget(self.customer_page)
        self.sro_table.setMinimumSize(QtCore.QSize(401, 0))
        self.sro_table.setMaximumSize(QtCore.QSize(16000000, 16777215))
        self.sro_table.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.sro_table.setObjectName("sro_table")
        self.sro_table.setColumnCount(6)
        self.sro_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sro_table.setHorizontalHeaderItem(5, item)
        self.sro_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_17.addWidget(self.sro_table)
        self.horizontalLayout_16.addLayout(self.verticalLayout_17)
        spacerItem39 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem39)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 10)
        self.horizontalLayout_16.setStretch(2, 1)
        self.horizontalLayout_16.setStretch(3, 10)
        self.horizontalLayout_16.setStretch(4, 1)
        self.verticalLayout_20.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem40 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem40)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.customer_page)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.phone_tbox = QtWidgets.QTextBrowser(self.customer_page)
        self.phone_tbox.setObjectName("phone_tbox")
        self.verticalLayout_5.addWidget(self.phone_tbox)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.customer_page)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.notes_tbox = QtWidgets.QTextBrowser(self.customer_page)
        self.notes_tbox.setObjectName("notes_tbox")
        self.verticalLayout_6.addWidget(self.notes_tbox)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_16 = QtWidgets.QLabel(self.customer_page)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.layaways_table = QtWidgets.QTableWidget(self.customer_page)
        self.layaways_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.layaways_table.setObjectName("layaways_table")
        self.layaways_table.setColumnCount(3)
        self.layaways_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaways_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaways_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaways_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_4.addWidget(self.layaways_table)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        spacerItem41 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem41)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 5)
        self.horizontalLayout_15.setStretch(2, 10)
        self.horizontalLayout_15.setStretch(4, 1)
        self.verticalLayout_20.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem42)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.customer_page)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.transactions_table = QtWidgets.QTableWidget(self.customer_page)
        self.transactions_table.setMinimumSize(QtCore.QSize(521, 0))
        self.transactions_table.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.transactions_table.setObjectName("transactions_table")
        self.transactions_table.setColumnCount(5)
        self.transactions_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.transactions_table.setHorizontalHeaderItem(4, item)
        self.transactions_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.transactions_table)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem43)
        self.horizontalLayout_14.setStretch(0, 2)
        self.horizontalLayout_14.setStretch(1, 10)
        self.horizontalLayout_14.setStretch(2, 2)
        self.verticalLayout_20.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem44)
        self.back_btn_customer = QtWidgets.QPushButton(self.customer_page)
        self.back_btn_customer.setObjectName("back_btn_customer")
        self.horizontalLayout_12.addWidget(self.back_btn_customer)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem45)
        self.verticalLayout_20.addLayout(self.horizontalLayout_12)
        self.verticalLayout_20.setStretch(0, 1)
        self.verticalLayout_20.setStretch(1, 10)
        self.verticalLayout_20.setStretch(2, 5)
        self.verticalLayout_20.setStretch(3, 6)
        self.verticalLayout_20.setStretch(4, 1)
        self.stackedWidget.addWidget(self.customer_page)
        self.sale_page = QtWidgets.QWidget()
        self.sale_page.setObjectName("sale_page")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.sale_page)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem46)
        self.label_23 = QtWidgets.QLabel(self.sale_page)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_17.addWidget(self.label_23)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem47)
        self.verticalLayout_21.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem48)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.sale_page)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.sale_basic_info = QtWidgets.QTableWidget(self.sale_page)
        self.sale_basic_info.setMinimumSize(QtCore.QSize(261, 231))
        self.sale_basic_info.setMaximumSize(QtCore.QSize(1670000, 1670000))
        self.sale_basic_info.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sale_basic_info.setObjectName("sale_basic_info")
        self.sale_basic_info.setColumnCount(1)
        self.sale_basic_info.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_basic_info.setHorizontalHeaderItem(0, item)
        self.verticalLayout_9.addWidget(self.sale_basic_info)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.sale_page)
        self.label_2.setMinimumSize(QtCore.QSize(36, 17))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.sale_totals = QtWidgets.QTableWidget(self.sale_page)
        self.sale_totals.setMinimumSize(QtCore.QSize(201, 311))
        self.sale_totals.setMaximumSize(QtCore.QSize(1670000, 1670000))
        self.sale_totals.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sale_totals.setObjectName("sale_totals")
        self.sale_totals.setColumnCount(1)
        self.sale_totals.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_totals.setHorizontalHeaderItem(0, item)
        self.verticalLayout_8.addWidget(self.sale_totals)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.horizontalLayout_18.addLayout(self.verticalLayout_10)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem49)
        self.sale_lines_table = QtWidgets.QTableWidget(self.sale_page)
        self.sale_lines_table.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.sale_lines_table.setObjectName("sale_lines_table")
        self.sale_lines_table.setColumnCount(5)
        self.sale_lines_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_lines_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_lines_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_lines_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_lines_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sale_lines_table.setHorizontalHeaderItem(4, item)
        self.sale_lines_table.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_18.addWidget(self.sale_lines_table)
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem50)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 1)
        self.horizontalLayout_18.setStretch(2, 1)
        self.horizontalLayout_18.setStretch(3, 20)
        self.horizontalLayout_18.setStretch(4, 1)
        self.verticalLayout_21.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem51)
        self.back_btn_sale = QtWidgets.QPushButton(self.sale_page)
        self.back_btn_sale.setObjectName("back_btn_sale")
        self.horizontalLayout_2.addWidget(self.back_btn_sale)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem52)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 10)
        self.horizontalLayout_2.setStretch(2, 10)
        self.verticalLayout_21.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.sale_page)
        self.layaway_page = QtWidgets.QWidget()
        self.layaway_page.setObjectName("layaway_page")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layaway_page)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem53)
        self.label_24 = QtWidgets.QLabel(self.layaway_page)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_20.addWidget(self.label_24)
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem54)
        self.verticalLayout_15.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem55)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layaway_table_1 = QtWidgets.QTableWidget(self.layaway_page)
        self.layaway_table_1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.layaway_table_1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.layaway_table_1.setObjectName("layaway_table_1")
        self.layaway_table_1.setColumnCount(1)
        self.layaway_table_1.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.layaway_table_1.setHorizontalHeaderItem(0, item)
        self.horizontalLayout.addWidget(self.layaway_table_1)
        self.layaway_table_2 = QtWidgets.QTableWidget(self.layaway_page)
        self.layaway_table_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.layaway_table_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.layaway_table_2.setObjectName("layaway_table_2")
        self.layaway_table_2.setColumnCount(1)
        self.layaway_table_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.layaway_table_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.layaway_table_2.setHorizontalHeaderItem(0, item)
        self.horizontalLayout.addWidget(self.layaway_table_2)
        self.horizontalLayout_22.addLayout(self.horizontalLayout)
        spacerItem56 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem56)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.layaway_page)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.layaway_initial_notes_tbox = QtWidgets.QTextBrowser(self.layaway_page)
        self.layaway_initial_notes_tbox.setObjectName("layaway_initial_notes_tbox")
        self.verticalLayout_12.addWidget(self.layaway_initial_notes_tbox)
        self.verticalLayout_12.setStretch(1, 10)
        self.horizontalLayout_22.addLayout(self.verticalLayout_12)
        spacerItem57 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem57)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 10)
        self.horizontalLayout_22.setStretch(2, 1)
        self.horizontalLayout_22.setStretch(3, 10)
        self.horizontalLayout_22.setStretch(4, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem58 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem58)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.layaway_page)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_14.addWidget(self.label_15)
        self.layaway_transaction_history_tbox = QtWidgets.QTextBrowser(self.layaway_page)
        self.layaway_transaction_history_tbox.setObjectName("layaway_transaction_history_tbox")
        self.verticalLayout_14.addWidget(self.layaway_transaction_history_tbox)
        self.horizontalLayout_21.addLayout(self.verticalLayout_14)
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem59)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.layaway_page)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.layaway_notes_tbox = QtWidgets.QTextBrowser(self.layaway_page)
        self.layaway_notes_tbox.setObjectName("layaway_notes_tbox")
        self.verticalLayout_13.addWidget(self.layaway_notes_tbox)
        self.horizontalLayout_21.addLayout(self.verticalLayout_13)
        spacerItem60 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem60)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 10)
        self.horizontalLayout_21.setStretch(2, 1)
        self.horizontalLayout_21.setStretch(3, 10)
        self.horizontalLayout_21.setStretch(4, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem61)
        self.back_btn_layaway = QtWidgets.QPushButton(self.layaway_page)
        self.back_btn_layaway.setObjectName("back_btn_layaway")
        self.horizontalLayout_19.addWidget(self.back_btn_layaway)
        spacerItem62 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem62)
        self.horizontalLayout_19.setStretch(0, 10)
        self.horizontalLayout_19.setStretch(1, 10)
        self.horizontalLayout_19.setStretch(2, 10)
        self.verticalLayout_15.addLayout(self.horizontalLayout_19)
        self.stackedWidget.addWidget(self.layaway_page)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1652, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_17.setText(_translate("MainWindow", "Old POS Data Viewer"))
        self.search_btn.setText(_translate("MainWindow", "Run a Search"))
        self.serialized_btn.setText(_translate("MainWindow", "See Serialized Inventory"))
        self.label_18.setText(_translate("MainWindow", "Search Results"))
        item = self.search_result_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.search_result_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First"))
        item = self.search_result_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last"))
        item = self.search_result_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address"))
        item = self.search_result_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "City"))
        item = self.search_result_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "State"))
        item = self.search_result_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Zip"))
        item = self.search_result_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Home Phone"))
        item = self.search_result_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Work Phone"))
        item = self.search_result_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Cell Phone"))
        item = self.search_result_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Added"))
        item = self.search_result_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Last"))
        self.back_btn_search_result.setText(_translate("MainWindow", "Back"))
        self.label_19.setText(_translate("MainWindow", "Search"))
        self.submit_search_btn.setText(_translate("MainWindow", "Search"))
        self.label_7.setText(_translate("MainWindow", "First Name"))
        self.label_6.setText(_translate("MainWindow", "General Search"))
        self.label_5.setText(_translate("MainWindow", "Last Name"))
        self.label_4.setText(_translate("MainWindow", "Phone #"))
        self.back_btn_search.setText(_translate("MainWindow", "Back"))
        self.label_20.setText(_translate("MainWindow", "Serialized Inventory"))
        self.serial_table.setSortingEnabled(True)
        item = self.serial_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Make"))
        item = self.serial_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.serial_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Serial #"))
        item = self.serial_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        item = self.serial_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Notes"))
        self.back_btn_serial.setText(_translate("MainWindow", "Back"))
        self.label_21.setText(_translate("MainWindow", "SRO"))
        item = self.sro_basic_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Service ID"))
        item = self.sro_basic_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.sro_basic_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Make"))
        item = self.sro_basic_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Model"))
        item = self.sro_basic_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date In"))
        item = self.sro_basic_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Finished On"))
        item = self.sro_basic_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Picked Up"))
        item = self.sro_basic_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        self.label_8.setText(_translate("MainWindow", "Service Request"))
        self.label_9.setText(_translate("MainWindow", "Work Performed"))
        self.sro_back_btn.setText(_translate("MainWindow", "Back"))
        self.label_22.setText(_translate("MainWindow", "Customer Info"))
        item = self.customer_table_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.customer_table_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "First"))
        item = self.customer_table_1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last"))
        item = self.customer_table_1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cmpny"))
        item = self.customer_table_1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.customer_table_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        item = self.customer_table_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Addr"))
        item = self.customer_table_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "City"))
        item = self.customer_table_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "State"))
        item = self.customer_table_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Zip"))
        item = self.customer_table_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Last"))
        item = self.customer_table_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        self.label_11.setText(_translate("MainWindow", "SRO"))
        item = self.sro_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date In"))
        item = self.sro_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date Done"))
        item = self.sro_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Picked Up"))
        item = self.sro_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Make"))
        item = self.sro_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Model"))
        item = self.sro_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "SRO ID"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Potential Phones</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Notes"))
        self.label_16.setText(_translate("MainWindow", "Layaways"))
        item = self.layaways_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Start"))
        item = self.layaways_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Balance"))
        item = self.layaways_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Layaway ID"))
        self.label_13.setText(_translate("MainWindow", "Transactions"))
        item = self.transactions_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.transactions_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Subtotal"))
        item = self.transactions_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tax"))
        item = self.transactions_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total"))
        item = self.transactions_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sale ID"))
        self.back_btn_customer.setText(_translate("MainWindow", "Back"))
        self.label_23.setText(_translate("MainWindow", "Transaction Info"))
        self.label.setText(_translate("MainWindow", "Sale Info"))
        item = self.sale_basic_info.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sale ID"))
        item = self.sale_basic_info.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.sale_basic_info.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Customer Name"))
        item = self.sale_basic_info.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        item = self.sale_basic_info.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Is Overring?"))
        item = self.sale_basic_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        self.label_2.setText(_translate("MainWindow", "Totals"))
        item = self.sale_totals.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Subtotal"))
        item = self.sale_totals.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tax"))
        item = self.sale_totals.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total"))
        item = self.sale_totals.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cash"))
        item = self.sale_totals.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Credit"))
        item = self.sale_totals.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Debit"))
        item = self.sale_totals.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Misc"))
        item = self.sale_totals.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        item = self.sale_lines_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.sale_lines_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Unit Cost"))
        item = self.sale_lines_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Item Discount"))
        item = self.sale_lines_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Item Total"))
        item = self.sale_lines_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        self.back_btn_sale.setText(_translate("MainWindow", "Back"))
        self.label_24.setText(_translate("MainWindow", "Layaway Info"))
        item = self.layaway_table_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Layaway ID"))
        item = self.layaway_table_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.layaway_table_1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.layaway_table_1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Start Date"))
        item = self.layaway_table_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        item = self.layaway_table_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pay Received"))
        item = self.layaway_table_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Balance Due"))
        item = self.layaway_table_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Initial Notes</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Transaction History</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Notes</span></p></body></html>"))
        self.back_btn_layaway.setText(_translate("MainWindow", "Back"))


