# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 869)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setObjectName("stackedWidget")
        self.start_page = QtWidgets.QWidget()
        self.start_page.setObjectName("start_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.start_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.search_btn = QtWidgets.QPushButton(self.start_page)
        self.search_btn.setObjectName("search_btn")
        self.gridLayout.addWidget(self.search_btn, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.start_page)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.start_page)
        self.search_result_page = QtWidgets.QWidget()
        self.search_result_page.setObjectName("search_result_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.search_result_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.back_btn = QtWidgets.QPushButton(self.search_result_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        self.back_btn.setObjectName("back_btn")
        self.gridLayout_2.addWidget(self.back_btn, 1, 1, 1, 1)
        self.data_table = QtWidgets.QTableWidget(self.search_result_page)
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(8)
        self.data_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table.setHorizontalHeaderItem(7, item)
        self.gridLayout_2.addWidget(self.data_table, 0, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(353, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(353, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.search_result_page)
        self.search_page = QtWidgets.QWidget()
        self.search_page.setObjectName("search_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.search_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 1, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.general_radio = QtWidgets.QRadioButton(self.search_page)
        self.general_radio.setText("")
        self.general_radio.setObjectName("general_radio")
        self.gridLayout_7.addWidget(self.general_radio, 7, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.search_page)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.search_button = QtWidgets.QPushButton(self.search_page)
        self.search_button.setObjectName("search_button")
        self.gridLayout_7.addWidget(self.search_button, 8, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.search_page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.general_search = QtWidgets.QLineEdit(self.search_page)
        self.general_search.setText("")
        self.general_search.setObjectName("general_search")
        self.gridLayout_7.addWidget(self.general_search, 7, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.search_page)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.last_search = QtWidgets.QLineEdit(self.search_page)
        self.last_search.setText("")
        self.last_search.setObjectName("last_search")
        self.gridLayout_7.addWidget(self.last_search, 5, 1, 1, 2)
        self.phone_search = QtWidgets.QLineEdit(self.search_page)
        self.phone_search.setText("")
        self.phone_search.setObjectName("phone_search")
        self.gridLayout_7.addWidget(self.phone_search, 1, 1, 1, 2)
        self.phone_radio = QtWidgets.QRadioButton(self.search_page)
        self.phone_radio.setText("")
        self.phone_radio.setObjectName("phone_radio")
        self.gridLayout_7.addWidget(self.phone_radio, 1, 0, 1, 1)
        self.last_radio = QtWidgets.QRadioButton(self.search_page)
        self.last_radio.setText("")
        self.last_radio.setObjectName("last_radio")
        self.gridLayout_7.addWidget(self.last_radio, 5, 0, 1, 1)
        self.first_radio = QtWidgets.QRadioButton(self.search_page)
        self.first_radio.setText("")
        self.first_radio.setObjectName("first_radio")
        self.gridLayout_7.addWidget(self.first_radio, 3, 0, 1, 1)
        self.first_search = QtWidgets.QLineEdit(self.search_page)
        self.first_search.setText("")
        self.first_search.setObjectName("first_search")
        self.gridLayout_7.addWidget(self.first_search, 3, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.search_page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_6.addLayout(self.gridLayout_7, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem10, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.search_page)
        self.serialized_page = QtWidgets.QWidget()
        self.serialized_page.setObjectName("serialized_page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.serialized_page)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.serialized_data = QtWidgets.QTableWidget(self.serialized_page)
        self.serialized_data.setObjectName("serialized_data")
        self.serialized_data.setColumnCount(5)
        self.serialized_data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.serialized_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.serialized_data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.serialized_data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.serialized_data.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.serialized_data.setHorizontalHeaderItem(4, item)
        self.gridLayout_8.addWidget(self.serialized_data, 0, 0, 1, 3)
        spacerItem11 = QtWidgets.QSpacerItem(404, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem11, 1, 0, 1, 1)
        self.back_btn_2 = QtWidgets.QPushButton(self.serialized_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn_2.sizePolicy().hasHeightForWidth())
        self.back_btn_2.setSizePolicy(sizePolicy)
        self.back_btn_2.setMinimumSize(QtCore.QSize(200, 0))
        self.back_btn_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.back_btn_2.setObjectName("back_btn_2")
        self.gridLayout_8.addWidget(self.back_btn_2, 1, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(406, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem12, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.serialized_page)
        self.sro_page = QtWidgets.QWidget()
        self.sro_page.setObjectName("sro_page")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.sro_page)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.data_table_3 = QtWidgets.QTableWidget(self.sro_page)
        self.data_table_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_table_3.sizePolicy().hasHeightForWidth())
        self.data_table_3.setSizePolicy(sizePolicy)
        self.data_table_3.setMaximumSize(QtCore.QSize(16777215, 308))
        self.data_table_3.setObjectName("data_table_3")
        self.data_table_3.setColumnCount(1)
        self.data_table_3.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_3.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_3.addWidget(self.data_table_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.sro_page)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.service_text = QtWidgets.QTextBrowser(self.sro_page)
        self.service_text.setObjectName("service_text")
        self.verticalLayout_3.addWidget(self.service_text)
        self.label_9 = QtWidgets.QLabel(self.sro_page)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.work_text = QtWidgets.QTextBrowser(self.sro_page)
        self.work_text.setObjectName("work_text")
        self.verticalLayout_3.addWidget(self.work_text)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.sro_page)
        self.layoutWidget_3.setGeometry(QtCore.QRect(270, 140, 193, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.back_btn_3 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.back_btn_3.setObjectName("back_btn_3")
        self.horizontalLayout_4.addWidget(self.back_btn_3)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.stackedWidget.addWidget(self.sro_page)
        self.customer_page = QtWidgets.QWidget()
        self.customer_page.setObjectName("customer_page")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.customer_page)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem15 = QtWidgets.QSpacerItem(368, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem15, 0, 0, 1, 1)
        self.data_table_5 = QtWidgets.QTableWidget(self.customer_page)
        self.data_table_5.setMaximumSize(QtCore.QSize(251, 231))
        self.data_table_5.setObjectName("data_table_5")
        self.data_table_5.setColumnCount(1)
        self.data_table_5.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_5.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table_5.setHorizontalHeaderItem(0, item)
        self.gridLayout_10.addWidget(self.data_table_5, 0, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.data_table_4 = QtWidgets.QTableWidget(self.customer_page)
        self.data_table_4.setMaximumSize(QtCore.QSize(241, 231))
        self.data_table_4.setObjectName("data_table_4")
        self.data_table_4.setColumnCount(1)
        self.data_table_4.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.data_table_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_table_4.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_7.addWidget(self.data_table_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.customer_page)
        self.pushButton_3.setMaximumSize(QtCore.QSize(151, 121))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.gridLayout_10.addLayout(self.horizontalLayout_7, 0, 2, 1, 2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.customer_page)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.tableWidget = QtWidgets.QTableWidget(self.customer_page)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 71))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.gridLayout_10.addLayout(self.verticalLayout_6, 1, 0, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.customer_page)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.customer_page)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_5.addWidget(self.textBrowser_4)
        self.gridLayout_10.addLayout(self.verticalLayout_5, 1, 2, 1, 2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.customer_page)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.customer_page)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(521, 0))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.verticalLayout_7.addWidget(self.tableWidget_2)
        self.gridLayout_10.addLayout(self.verticalLayout_7, 2, 0, 1, 3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.customer_page)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.customer_page)
        self.tableWidget_3.setMaximumSize(QtCore.QSize(401, 16777215))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.verticalLayout_4.addWidget(self.tableWidget_3)
        self.gridLayout_10.addLayout(self.verticalLayout_4, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.customer_page)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_btn.setText(_translate("MainWindow", "Run a Search"))
        self.pushButton_2.setText(_translate("MainWindow", "See Serialized Inventory"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
        item = self.data_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.data_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Last"))
        item = self.data_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "First"))
        item = self.data_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Home Phone"))
        item = self.data_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Work Phone"))
        item = self.data_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Company"))
        item = self.data_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Last Active"))
        item = self.data_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Added"))
        self.label_4.setText(_translate("MainWindow", "Phone #"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.label_5.setText(_translate("MainWindow", "Last Name"))
        self.label_6.setText(_translate("MainWindow", "General Search"))
        self.label_7.setText(_translate("MainWindow", "First Name"))
        item = self.serialized_data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Make"))
        item = self.serialized_data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.serialized_data.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Serial #"))
        item = self.serialized_data.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        item = self.serialized_data.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Notes"))
        self.back_btn_2.setText(_translate("MainWindow", "Back"))
        item = self.data_table_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Service ID"))
        item = self.data_table_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.data_table_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Make"))
        item = self.data_table_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Model"))
        item = self.data_table_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date In"))
        item = self.data_table_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Finished On"))
        item = self.data_table_3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Picked Up"))
        item = self.data_table_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        self.label_8.setText(_translate("MainWindow", "Service Request"))
        self.label_9.setText(_translate("MainWindow", "Work Performed"))
        self.back_btn_3.setText(_translate("MainWindow", "Back"))
        item = self.data_table_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.data_table_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "First"))
        item = self.data_table_5.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last"))
        item = self.data_table_5.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Company"))
        item = self.data_table_5.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.data_table_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        item = self.data_table_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.data_table_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "City"))
        item = self.data_table_4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "State"))
        item = self.data_table_4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Zip"))
        item = self.data_table_4.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Last Activity"))
        item = self.data_table_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Values"))
        self.pushButton_3.setText(_translate("MainWindow", "Layaways"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Potential Phones</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Notes"))
        self.label_13.setText(_translate("MainWindow", "Transactions"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Subtotal"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tax"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total"))
        self.label_11.setText(_translate("MainWindow", "SRO"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date In"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date Done"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Picked Up"))


